language: node_js
node_js:
  - 'stable'

jobs:
  include:
    - stage: lint
      install:
        - npm ci
      script:
        - npm run lint

    - stage: test
      addons:
        mariadb: '10.3'
      before_install:
        - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS test_jiskefet;'
      install:
        - npm ci
      script:
        - npm test
      after_success:
        - codecov

notifications:
  slack: jiskefet:cGYsslE19X0IqoUwQXwAR9tT
